import { defineConfig, devices } from '@playwright/test';
// import { nxE2EPreset } from '@nx/playwright/preset';
// import { workspaceRoot } from '@nx/devkit';

/* ported code */
// import { workspaceRoot } from '@nx/devkit';
const workspaceRoot = __dirname.replace('apps/second-app-e2e', '');
// import { isUsingTsSolutionSetup } from '@nx/js/src/utils/typescript/ts-solution-setup';
export function isUsingTsSolutionSetup(): boolean {
  // const tree = new FsTree(workspaceRoot, false);

  return (
    // isUsingPackageManagerWorkspaces(tree) &&
    // isWorkspaceSetupWithTsSolution(tree)
    true
  );
}
// import { defineConfig } from '@playwright/test';
import { lstatSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';

export interface NxPlaywrightOptions {
  /**
   * The directory where the e2e tests are located.
   * @default './src'
   **/
  testDir?: string;
}

/**
 * nx E2E Preset for Playwright
 * @description
 * this preset contains the base configuration
 * for your e2e tests that nx recommends.
 * By default html reporter is configured
 * along with the following browsers:
 * - chromium
 * - firefox
 * - webkit
 * These are generated by default.
 *
 * you can easily extend this within your playwright config via spreading the preset
 * @example
 * export default defineConfig({
 *   ...nxE2EPreset(__filename, options)
 *   // add your own config here
 * })
 *
 * @param pathToConfig will be used to construct the output paths for reporters and test results
 * @param options optional configuration options
 */
export function nxE2EPreset(
  pathToConfig: string,
  options?: NxPlaywrightOptions
) {
  const normalizedPath = lstatSync(pathToConfig).isDirectory()
    ? pathToConfig
    : dirname(pathToConfig);
  const projectPath = relative(workspaceRoot, normalizedPath);
  const offset = relative(normalizedPath, workspaceRoot);

  const isTsSolutionSetup = isUsingTsSolutionSetup();

  const testResultOuputDir = isTsSolutionSetup
    ? 'test-output/playwright/output'
    : join(offset, 'dist', '.playwright', projectPath, 'test-output');
  const reporterOutputDir = isTsSolutionSetup
    ? 'test-output/playwright/report'
    : join(offset, 'dist', '.playwright', projectPath, 'playwright-report');

  return defineConfig({
    testDir: options?.testDir ?? './src',
    outputDir: testResultOuputDir,
    /* Run tests in files in parallel */
    fullyParallel: true,
    /* Fail the build on CI if you accidentally left test.only in the source code. */
    forbidOnly: !!process.env.CI,
    /* Retry on CI only */
    retries: process.env.CI ? 2 : 0,
    /* Opt out of parallel tests on CI. */
    workers: process.env.CI ? 1 : undefined,
    /* Reporter to use. See https://playwright.dev/docs/test-reporters */
    reporter: [
      [
        'html',
        {
          outputFolder: reporterOutputDir,
        },
      ],
    ],
  });
}
/* end ported code */

// For CI, you may want to set BASE_URL to the deployed application.
const baseURL = process.env['BASE_URL'] || 'http://localhost:4300';

/**
 * Read environment variables from file.
 * https://github.com/motdotla/dotenv
 */
// require('dotenv').config();

/**
 * See https://playwright.dev/docs/test-configuration.
 */
export default defineConfig({
  ...nxE2EPreset(__filename, { testDir: './src' }),
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    baseURL,
    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',
  },
  /* Run your local dev server before starting the tests */
  webServer: {
    // command: 'npx nx run second-app:preview',
    // TODO: Why doesn't this work as just 'npm run preview -w apps/second-app' like it is set up for first-app?
    command: 'npm run preview -w apps/second-app',
    url: 'http://localhost:4300',
    reuseExistingServer: true,
    cwd: workspaceRoot
  },
  projects: [
    {
      name: "chromium",
      use: { ...devices["Desktop Chrome"] },
    },

    {
      name: "firefox",
      use: { ...devices["Desktop Firefox"] },
    },

    {
      name: "webkit",
      use: { ...devices["Desktop Safari"] },
    },

    // Uncomment for mobile browsers support
    /* {
      name: 'Mobile Chrome',
      use: { ...devices['Pixel 5'] },
    },
    {
      name: 'Mobile Safari',
      use: { ...devices['iPhone 12'] },
    }, */

    // Uncomment for branded browsers
    /* {
      name: 'Microsoft Edge',
      use: { ...devices['Desktop Edge'], channel: 'msedge' },
    },
    {
      name: 'Google Chrome',
      use: { ...devices['Desktop Chrome'], channel: 'chrome' },
    } */
  ],
});
